update pipeline

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -1,14 +1,74 @@
-# ASP.NET Core
-# Build and test ASP.NET Core projects targeting .NET Core.
-# Add steps that run tests, create a NuGet package, deploy, and more:
-# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
+# Docker image
+# Build a Docker image to deploy, run, or push to a container registry.
+# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
+# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
 
 pool:
   vmImage: 'Ubuntu 16.04'
 
 variables:
-  buildConfiguration: 'Release'
+  imageName: '$(dockerId)/activityreservation'
 
 steps:
-- script: dotnet build --configuration $(buildConfiguration)
-  displayName: 'dotnet build $(buildConfiguration)'
+
+- script: |
+    docker build -f Dockerfile -t $(imageName) .
+    docker login -u $(dockerId) -p $(pswd)
+    docker push $(imageName)
+
+- task: SSH@0
+  displayName: 'Run shell inline on remote machine'
+  inputs:
+    sshEndpoint: 'weihanli-vm'
+    runOptions: inline
+
+    inline: |
+     containers=$(docker ps -q --filter name=activityreservation)
+     if test -n "$containers"; then
+      docker stop $(docker ps -q --filter name=activityreservation) >> /dev/null 2>&1
+      rc=$?
+      if [[ $rc != 0 ]];
+      then
+       echo 'failed to stop container...'
+       exit $rc;
+      fi
+     fi
+     
+     containers1=$(docker ps -q -a --filter name=activityreservation)
+     if test -n "$containers1"; then
+      docker rm $(docker ps -q -a --filter name=activityreservation) >> /dev/null 2>&1
+      rc=$?
+      if [[ $rc != 0 ]];
+      then
+       echo 'failed to remove container...'
+       exit $rc;
+      fi
+     fi
+     
+     
+     docker pull $(imageName):latest >> /dev/null 2>&1
+     rc=$?
+     if [[ $rc != 0 ]];
+     then
+      echo 'failed to pull container...'
+      exit $rc;
+     fi
+     
+     docker run -d -p 6010:80 --name activityreservation $(imageName):latest >> /dev/null 2>&1
+     rc=$?
+     if [[ $rc != 0 ]];
+     then
+      echo 'failed to run container...'
+      exit $rc;
+     fi
+     
+     danglings=$(docker images -f "dangling=true" -q)
+     if test -n "$danglings"; then
+      docker rmi $(docker images -f "dangling=true" -q) >> /dev/null 2>&1
+      rc=$?
+      if [[ $rc != 0 ]];
+      then
+       echo 'failed to remove danglings container...'
+       exit $rc;
+      fi
+     fi
